owner: CommandCodeAI
repo: commandcode-status

sites:
  - name: Command Code
    url: https://api.commandcode.ai

status-website:
  cname: status.commandcode.ai
  logoUrl: https://raw.githubusercontent.com/CommandCodeAI/docs-images/refs/heads/main/design/logo/logo-symbol.svg
  name: Command Code Status
  navbar:
    - title: Command Code
      href: https://commandcode.ai
    - title: Status
      href: /
    - title: Subscribe on GitHub
      href: https://github.com/$OWNER/$REPO/issues
status-page:
  faviconSvg: https://raw.githubusercontent.com/CommandCodeAI/status/master/assets/favicon.svg
i18n:
  footer: ''
