owner: CommandCodeAI
repo: commandcode-status

sites:
  - name: Command Code
    url: https://api.commandcode.ai

status-website:
  cname: status.commandcode.ai
  logoUrl: https://raw.githubusercontent.com/CommandCodeAI/docs-images/refs/heads/main/commandcode/logo/commandcode-light.svg
  name: Command Code Status
  introTitle: "**Command Code** Status"
  introMessage: This is the status page for [Command Code](https://commandcode.ai), showing real-time uptime and incident history.
  navbar:
    - title: Command Code
      href: https://commandcode.ai
    - title: Status
      href: /
    - title: Subscribe on GitHub
      href: https://github.com/$OWNER/$REPO/issues
status-page:
  faviconSvg: https://raw.githubusercontent.com/langbaseinc/status/master/assets/favicon.svg
i18n:
  footer: ''
